### ISSUE TITLE
Bad Link in ReadMe

### ISSUE THREAD

**Issue by jimender2** [joyja/ignition-framework#1]
In your readme file you point us to https://ignition.jarautomation.io/
This URL then redirects me to to https://10.138.186.138/data/perspective/client/playground/  It times out for me.  Is there any fix for this?

**Comment by joyja** [comment]
I had this issue briefly too. The original problem was with my reverse proxy server and it remained even after I fixed the server because Chrome caches 301 redirects. Other browsers and my phone still worked. Try clearing your browser cache, that's what fixed it for me.

**Comment by jimender2** [comment]
I was using Firefox to open it.  When i went and opened it in a new private window it worked fine.   What reverse proxy are you using and are you offloading your ssl to the reverse proxy?

**Comment by joyja** [comment]
nginx and yes (Let's Encrypt with the nginx plugin)
